project:
  type: website
  output-dir: docs

website:
  title: "Openscapes Events"
  site-url: https://openscapes.org
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes Core Team"
 
  navbar:
    logo: openscapes_hex.png
    href: https://openscapes.org
    right:
      - text: "Events"
        href: index.html
      - text: "Home"
        href: https://openscapes.org
      - icon: github
        href: https://github.com/openscapes/events
      - icon: twitter
        href: https://twitter.com/openscapes
        
format:
  html:
    theme: 
      - lumen 
      #- custom.scss
    
    # notes on YAML: https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/#inheriting-yaml-settings



