project:
  type: website

website:
  title: "Openscapes Events"
  site-url: https://openscapes.org
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes Core Team"
 
  navbar:
    logo: images/openscapes_hex.png
    href: https://openscapes.org
    right:
      - text: "Events"
        href: index.html
      - text: "Home"
        href: https://openscapes.org
      - icon: github
        href: https://github.com/opencapes/events
      - icon: twitter
        href: https://twitter.com/openscapes
        
format:
  html:
    theme: ember.scss # or cosmo with black banner



