---
title: "CS&S Openscapes Champions Cohort"
description: |
  Openscapes Champions Cohort sponsored by Code for Science and Society (CS&S)
author:
  - name: "Openscapes and CS&S"
date: 2021-05-07
categories:
  - mentorship opportunity
  - registration open
output:
  distill::distill_article:
    self_contained: false
draft: TRUE    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**This is a professional development and leadership opportunity for data-intensive environmental research.**

[**Openscapes**](https://openscapes.org) helps research groups reimagine data analysis, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive research communities. 

**CS&S Openscapes Champions** is a professional development and leadership opportunity around open practices for data-driven science. This two-month remote program is not about teaching you to code. It is about changing your relationship with code and data, and cultivating a more collaborative and inclusive research group. You will participate as a team with others from your research group, learning how to reframe data analysis as a collaborative effort rather than an individual burden. You will be mentored to supercharge your research by leveraging open source tools (e.g. R/RStudio, GitHub) to make your research more efficient and your data analyses more reproducible. For more information and guidance about how to select your team, please visit [openscapes.org/champions](https://www.openscapes.org/champions/).

**Program Overview:** We will meet four times over two months, on alternating Fridays in 2021.

- **Dates: **May 7, May 21, June 4, June 18
- **Times: **12:00-1:30pm PST 
- **Where:** remotely, via Zoom
- **Who: **Cohort of 6-8 environmental research teams. Each team consists of a team lead (faculty, lecturer, program manager, etc) and up to 4 team members of your choice (students, researchers, analysts, etc). 
- **Expected time commitment:** 5hrs/month for 2 months, which accounts for a 3 hours/month of synchronous Zoom calls, and the remaining time for collaborating with your research group in between calls.

**Nominate your team to participate**

Nominate your team by filling out this [Google Form] by March 26, 2021. Please submit one nomination per team, preferably by the team lead (faculty, project manager. principal investigator, etc). We will confirm participation by early April 2021. 

TODO: Image: Logos
